### PR TITLE
Allow ECMAScript 6 in jshint-config

### PR DESCRIPTION
**Pull request by pjasiun**

### CODE REVIEW

**Comment by Reinmar** [comment]
I would like to keep the ES6 specific preset in a separate branch. Otherwise it won't be easy to merge `master` to other related project like CKEditor 4.

**Comment by Reinmar** [comment]
Beside... it does not seem to work... It looks very weird because if I rune JSCS in CLI mode everything is fine. But something is wrong with grunt-jscs ;|.

**Comment by fredck** [comment]
At the current stage, shouldn't these be project specific configurations?

**Comment by Reinmar** [comment]
There will be specific for ES6 JSCS and perhaps JSHint rules. Better to keep them in one place.

**Comment by fredck** [comment]
Ok, it makes sense.

**Comment by Reinmar** [comment]
BTW. I lost an hour on this, because `esnext` option did not work for me when I was running grunt-jscs but was working ok when I was using JSCS right from the console. I even removed `node_modules/grunt-jscs/` totally and installed it again and nothing...

1 hour later, after I lost all my hair I decided to go with `rm -rf node_modules/`... Guess what. Now it works. I even checked in my bash history that I really reinstalled grunt-jscs from scratch at the beginning. Beside that I've run `npm update` couple of times too. Big WTF.

**Pull request closed without merging**
